### ISSUE TITLE
libraries not found

### ISSUE THREAD

**Issue by pzs7602** [aj-ames/Hermes-Deepstream#1]
errors occur when linking the hermes-app:
/usr/bin/ld: cannot find -lcurl
/usr/bin/ld: cannot find -lgnutls
/usr/bin/ld: cannot find -lboost_program_options
/usr/bin/ld: cannot find -lboost_filesystem
/usr/bin/ld: cannot find -lboost_context
/usr/bin/ld: cannot find -lboost_coroutine
/usr/bin/ld: cannot find -lboost_log
/usr/bin/ld: cannot find -lboost_log_setup
/usr/bin/ld: cannot find -lboost_regex

am I missing these libs?

**Comment by kingardor** [comment]
Can you try the following commands pls - 

For boost
```sh
sudo apt install libboost-all-dev
```

For gnutls
```sh
sudo apt install gnutls-dev
```

For curl
```sh
sudo apt install libcurl4-openssl-dev
```

**Comment by pzs7602** [comment]
that works! thanks!

**Comment by kingardor** [comment]
Great!
